# Constructing Machine Learning Models From Scratch

> In this notebook we will be building the ML models from the scratch and we will race it aganist the different prebuilt model , already present in the library.

> > First we will start by building the logistic regression model

> > > we will start by loading the dataset 

Let's see some of the dataset information and what is our goal regarding it.
1. Two Classes: Low Workload versus Medium Workload
2. Number of Samples: 180 for each class
3. Sampling Rate: 256Hz

For each sample
- Number of Channels: 62
- Number of Data Points: 512
Evaluation: You should use the five-Fold Cross-Validation to evaluate the classification performance.

In [1]:
import scipy.io as io#importing the library to import the data

In [2]:
data = io.loadmat('../input/building-ml-models-from-scratch/WLDataCW.mat')#importing the data

In [3]:
print('the length: '+ str(len(data)))#checking the number of keys

the length: 5


In [4]:
print(data.keys())#show the names of the keys

dict_keys(['__header__', '__version__', '__globals__', 'data', 'label'])


In [5]:
print(data['__globals__'])

[]


In [6]:
data_only = data["data"]#assiging it to the new variable,

#so here we are assigning the data variable from our main dataset to the new variable

In [7]:
label = data["label"]#assigning the label to the new variable

In [8]:
print(data_only.shape)

(62, 512, 360)


In [9]:
print(label.shape)

(1, 360)


The dimension of the data is 62.512.360, where 62 is the number of channels, 512 is the data points for each sample, and 360 is the number of samples. In the variable label, 0 indicates the class of low workload and 1 indicates the class of medium workload